### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#39]
Just for my reference right now. 

Listing some UI improvement ideas:

## Look and feel

We want to make the look and feel of the revealgenomics UI to match (wherever possible) that of the cohort selector developed by @mmccorry. Examples:

- [x] purple color on the banner
- [x] fonts and font sizes 
- [x] more to follow

## Study tree

- [ ] Level 3 and 4 of `Studies` tree can be collapsed (`Gene Expression` + `RNA-seq` = `Gene Expression (RNA-seq)`) (**`Priority: 2`**)
- [ ] No way to unselect a selection in `Study tree` -- elsewhere at another deployment, I have seen folks use a check-box instead of selections. That might allow easier unselections. (**`Priority: 1`**)
- [x] Study tree selection should not fire off new queries to DB while user is browsing other pipelines. Only a new selection should activate queries to DB. (**`Priority: 1`**)
- [x] Study tree throws warnings after [this commit](https://github.com/Paradigm4/revealgenomics-ui/commit/5c9b5b614729c4543788a0bee588ce44548b2920) was introduced to make the tree run faster (https://github.com/Paradigm4/revealgenomics-ui/issues/22) (**`Priority: 2`**)

## Gene list

- [x] Populate gene symbol as well as gene name in the `Genes` selectize. Search should be by gene symbol as well as gene full name (~~this requires some DB work by me first~~) (**`Priority: 2`**)
- [ ] Add modal for gene lists https://github.com/Paradigm4/revealgenomics-ui/issues/34 (**`Priority: 2`**)

## Miscellaneous

- [ ] (Copying your suggestion) Would suggest moving "REVEAL(TM) Genomics" up to where you have the P4 logo, so that it still shows if the sidebar is hidden, and maybe moving the logo to the right side of the header? This way the application title is always visible and it will show up in the browser tab name (e.g., in Chrome). Not sure the best placement for the logo (**`Priority: 2`**)
Adding addition minor item from our discussion earlier this morning:
- [x] Display study name as header in main panel to communicate what data user is viewing **(priority: 1)**
- [ ] Add a favicon (**priority: 3**)
- [x] Improve scroll bar for Study tree (**priority: 1**)
- [ ] Add search functionality to Study tree (**priority: 2**)

**Comment by ksens** [comment]
@mmccorry 

Does this look closer to the cohort selector now? See my above referenced commit. 

![image](https://user-images.githubusercontent.com/13973052/54294414-71244b80-45d7-11e9-9d51-14fe247cb7ed.png)

1. What about the black sidebar? Did you change that also? 
2. Also where are your settings for font and font sizes? Seemed to me that your font size was smaller (I might be wrong too).

**Comment by mmccorry** [comment]
@ksens 
Yes, what you changed in the above commit is how I got the purple theme.

1. Sidebar color is not different from what you have
2. Haven't specified differences for font sizes except in the tiles (`shinydashboard::box` elements) in the main panel.

Would suggest moving "REVEAL(TM) Genomics" up to where you have the P4 logo, so that it still shows if the sidebar is hidden, and maybe moving the logo to the right side of the header?  This way the application title is always visible and it will show up in the browser tab name (e.g., in Chrome).  Not sure the best placement for the logo -- will think on it; I should add it to the Cohort Selector as well.

**Comment by ksens** [comment]
@mmccorry 

Listing some UI improvement ideas:

## Study tree

- [ ] Level 3 and 4 of `Studies` tree can be collapsed (`Gene Expression` + `RNA-seq` = `Gene Expression (RNA-seq)`)
- [ ] No way to unselect a selection in `Study tree` -- elsewhere at another deployment, I have seen folks use a check-box instead of selections. That might allow easier unselections. 
- [ ] Study tree selection should not fire off new queries to DB while user is browsing other pipelines. Only a new selection should activate queries to DB. 
- [ ] Study tree throws warnings after [this commit](https://github.com/Paradigm4/revealgenomics-ui/commit/5c9b5b614729c4543788a0bee588ce44548b2920) was introduced to make the tree run faster (https://github.com/Paradigm4/revealgenomics-ui/issues/22)

## Gene list

- [ ] Populate gene symbol as well as gene name in the `Genes` selectize. Search should be by gene symbol as well as gene full name (this requires some DB work by me first)
- [ ] Add modal for gene lists https://github.com/Paradigm4/revealgenomics-ui/issues/34

## Miscellaneous

- [ ] (Copying your suggestion) Would suggest moving "REVEAL(TM) Genomics" up to where you have the P4 logo, so that it still shows if the sidebar is hidden, and maybe moving the logo to the right side of the header? This way the application title is always visible and it will show up in the browser tab name (e.g., in Chrome). Not sure the best placement for the logo
- [ ] Remove PCA tab (as it is not functional)
- [ ] Populate samples tab (https://github.com/Paradigm4/revealgenomics-ui/issues/17)

**Comment by ksens** [comment]
Updated previous comment

- [ ] Add a favicon (priority: 3)
- [ ] Improve scroll bar for Study tree

**Comment by mmccorry** [comment]
Adding addition minor item from our discussion earlier this morning:

- [ ] Display study name as header in main panel to communicate what data user is viewing **(priority: 1)**

**Comment by ksens** [comment]
@mmccorry 

I consolidated all action items to the first post on this thread (i.e. at the very top). Should ease tracking stuff. 

BTW found one item for discussion https://github.com/Paradigm4/revealgenomics-ui/issues/27#issuecomment-475235997

**Comment by ksens** [comment]
Revised list is at #43. Closing issue here.
