### ISSUE TITLE
UI improvements assigned to @ksens

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#40]
## Miscellaneous

- [x] Remove PCA tab (as it is not currently functional) (**`Priority: 1`**)
- [x] Populate samples tab (https://github.com/Paradigm4/revealgenomics-ui/issues/17) (**`Priority: 1`**)
- [x] Load gene full names (for use in #39)
- [x] Load a few gene lists so that gene list modal dialog box can work (#39)
- [x] Gene expression plots should display gene names instead of Ensembl gene id-s

Assigning some of the issues from #39 to myself.

**Comment by ksens** [comment]
@mmccorry 

Gene symbol full names are now populated wherever available. You should get the full name in the UI at https://github.com/Paradigm4/revealgenomics-ui/blob/master/dashboard/app.R#L238 (might need to restart R session in order for cache to refresh)

**Comment by mmccorry** [comment]
@ksens 
Super, I'll make the update for the selectize javascript rendering

**Comment by ksens** [comment]
@mmccorry 

A few sample gene lists are now available. This code is not yet called in the app, so I am providing an example below:

```R
rm(list=ls())
library(revealgenomics)
creds_file = '~/.revealgenomics-ui-config.json'
con = rg_connect2(username = read_json(creds_file)$`user-name`, password = read_json(creds_file)$`user-password`)
genelists = get_genelist(con = con)
genelists
#   genelist_id            name                                 description public       owner             created
# 1           1   RAS subfamily https://en.wikipedia.org/wiki/Ras_subfamily   TRUE public_user 2019-03-15 16:16:44
# 2           2 Oncogene List 1                    List of common oncogenes   TRUE secure_user 2019-03-15 16:18:08
#               updated gene_count
# 1 2019-03-15 16:16:44          3
# 2 2019-03-15 16:18:08          6

search_genelist_gene(genelist = genelists[1, ], con = con)
#   genelist_gene_id genelist_id gene_symbol_id gene_symbol                   full_name             created
# 1                1           1           6782        KRAS KRAS proto-oncogene, GTPase 2019-03-15 16:26:37
# 2                2           1          13747        HRAS HRas proto-oncogene, GTPase 2019-03-15 16:26:37
# 3                3           1          21457        NRAS NRAS proto-oncogene, GTPase 2019-03-15 16:26:37

search_genelist_gene(genelist = genelists[2, ], con = con)
#   genelist_gene_id genelist_id gene_symbol_id gene_symbol                            full_name             created
# 1                4           2            310       BRCA1         BRCA1, DNA repair associated 2019-03-15 16:30:30
# 2                5           2           6833         VHL   von Hippel-Lindau tumor suppressor 2019-03-15 16:30:30
# 3                6           2           6991         APC APC, WNT signaling pathway regulator 2019-03-15 16:30:30
# 4                7           2           7847       BRCA2         BRCA2, DNA repair associated 2019-03-15 16:30:30
# 5                8           2          13162        PTEN       phosphatase and tensin homolog 2019-03-15 16:30:30
# 6                9           2          17192         NF1                      neurofibromin 1 2019-03-15 16:30:30

# Or a quicker way of accessing the info required in the app
get_genelist_gene_symbols(con = con)
#   genelist_id gene_symbol
# 1           1        HRAS
# 2           1        NRAS
# 3           1        KRAS
# 4           2         NF1
# 5           2         VHL
# 6           2       BRCA1
# 7           2       BRCA2
# 8           2         APC
# 9           2        PTEN
```

PS: 

1. You might need to restart R session as I pushed a package update just now. 
2. Folks get different levels of access to gene lists based on their login -- so the public user (whose credentials are stored in the `.json` file above) has different access than `secure_user` (password shared separately)

**Comment by ksens** [comment]
Resolved request for plotting gene symbols instead of Ensembl ID-s via https://github.com/Paradigm4/revealgenomics/commit/7b5c86b272fc4e83c2fe38a35388b84a7ef6cc1e
